language: ruby

services:
  - mysql

cache:
  directories:
    - $HOME/.yarn-cache

before_install:
  - nvm install $(cat .nvmrc)
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

bundler_args: --without production

before_script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bin/rails db:setup
  - yarn install

script:
  - bundle exec rspec
  - bundle exec rubocop -R
  - yarn lint
  - NODE_ENV=production yarn build
